services:
  web:
    build: .
    command: gunicorn bar_app.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=bar_site.settings
    depends_on:
      - migrate

  migrate:
    build: .
    command: python manage.py migrate
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=bar_site.settings