# Generated by Django 5.2.5 on 2025-08-27 08:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chiave', models.CharField(max_length=50, unique=True)),
                ('valore', models.CharField(max_length=100)),
                ('attivo', models.BooleanField(default=False)),
                ('codice', models.CharField(default='', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chiave', models.CharField(max_length=50, unique=True)),
                ('valore', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Magazzino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('quantita', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('costo_acquisto', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Costo di acquisto')),
                ('soglia_minima', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Opzione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chiave', models.CharField(max_length=50, unique=True)),
                ('valore', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chiave', models.CharField(max_length=50, unique=True)),
                ('valore', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComponenteMagazzino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita_utilizzata', models.FloatField()),
                ('percentuale_maggiorazione', models.FloatField(default=0)),
                ('bloccante', models.BooleanField(default=True, help_text="Se attivo, l'esaurimento blocca la preparazione")),
                ('magazzino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bar.magazzino')),
            ],
        ),
        migrations.CreateModel(
            name='Ordine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creato', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.CharField(max_length=40)),
                ('utente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('stato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bar.stato')),
            ],
        ),
        migrations.CreateModel(
            name='Postazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chiave', models.CharField(max_length=50, unique=True)),
                ('valore', models.CharField(max_length=100)),
                ('box_associati', models.ManyToManyField(blank=True, related_name='box_associati', to='bar.box')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Prodotto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stato', models.CharField(choices=[('valido', 'Valido'), ('annullato', 'Annullato')], default='valido', max_length=10)),
                ('componenti_magazzino', models.ManyToManyField(related_name='distinta_base', through='bar.ComponenteMagazzino', to='bar.magazzino')),
            ],
        ),
        migrations.AddField(
            model_name='componentemagazzino',
            name='prodotto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bar.prodotto'),
        ),
        migrations.CreateModel(
            name='Sottocategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chiave', models.CharField(max_length=50, unique=True)),
                ('valore', models.CharField(max_length=100)),
                ('flag_subito_completato', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bar.categoria')),
                ('opzioni_abilitate', models.ManyToManyField(blank=True, related_name='opzioni_abilitate', to='bar.opzione')),
                ('postazione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bar.postazione')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='prodotto',
            name='sottocategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bar.sottocategoria'),
        ),
        migrations.AddField(
            model_name='postazione',
            name='sottocategorie_associate',
            field=models.ManyToManyField(blank=True, related_name='sottocategorie_associate', to='bar.sottocategoria'),
        ),
        migrations.CreateModel(
            name='OrdineRiga',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantita', models.PositiveIntegerField()),
                ('opzioni', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bar.opzione')),
                ('ordine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bar.ordine')),
                ('utente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('prodotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bar.prodotto')),
                ('stato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bar.stato')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postazione_predefinita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bar.postazione')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BoxAllocazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attivo', models.BooleanField(default=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bar.box')),
                ('ordine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bar.ordine')),
                ('postazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bar.postazione')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('ordine', 'postazione', 'attivo'), name='unique_active_box_per_postazione_ordine')],
            },
        ),
    ]
