# Generated by Django 5.2.3 on 2025-06-30 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creato', models.DateTimeField(auto_now_add=True)),
                ('stato', models.CharField(choices=[('in_attesa', 'In Attesa'), ('in_preparazione', 'In Preparazione'), ('completato', 'Completato')], default='in_attesa', max_length=20)),
                ('cliente', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Prodotto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.CreateModel(
            name='OrdineRiga',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantita', models.PositiveIntegerField()),
                ('stato', models.CharField(choices=[('in_attesa', 'In Attesa'), ('in_preparazione', 'In Preparazione'), ('completato', 'Completato')], default='in_attesa', max_length=20)),
                ('ordine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bar.ordine')),
                ('prodotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bar.prodotto')),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
