# Generated by Django 5.2.5 on 2025-08-27 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='codice',
        ),
    ]
