# Generated by Django 5.2.5 on 2025-08-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0002_remove_box_codice'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='codice',
            field=models.IntegerField(default=1),
        ),
    ]
