# Generated by Django 5.2.3 on 2025-06-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0002_ordine_prodotto_remove_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodotto',
            name='sottocategoria',
            field=models.CharField(choices=[('bar', 'bar'), ('cucina', 'cucina')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='prodotto',
            name='categoria',
            field=models.CharField(choices=[('bar', 'bar'), ('cucina', 'cucina')], default='bar', max_length=50),
        ),
    ]
