# Generated by Django 5.2.3 on 2025-06-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0003_prodotto_sottocategoria_alter_prodotto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodotto',
            name='sottocategoria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
