# Generated by Django 5.2.3 on 2025-06-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0004_alter_prodotto_sottocategoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodotto',
            name='sottocategoria',
            field=models.CharField(blank=True, choices=[('patatine', 'patatine'), ('piastra', 'piastra'), ('affettato', 'affettato'), ('gnocco', 'gnocco'), ('', '-')], max_length=50, null=True),
        ),
    ]
