# Generated by Django 5.2.3 on 2025-06-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0005_alter_prodotto_sottocategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordineriga',
            name='opzioni',
            field=models.CharField(choices=[('cipolla', 'Cipolla'), ('peperoni', 'Peperoni'), ('cipolla&peperoni', 'Cipolla e peperoni'), ('asperto', 'Asporto'), ('meta', 'Taglia a metà')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='prodotto',
            name='sottocategoria',
            field=models.CharField(blank=True, choices=[('patatine', 'patatine'), ('piastra', 'piastra'), ('special', 'special'), ('affettato', 'affettato'), ('gnocco', 'gnocco'), ('', '-')], max_length=50, null=True),
        ),
    ]
