# Generated by Django 5.2.4 on 2025-07-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0007_parametri'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chiave', models.CharField(max_length=50, unique=True)),
                ('valore', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Opzione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chiave', models.CharField(max_length=50, unique=True)),
                ('valore', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sottocategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chiave', models.CharField(max_length=50, unique=True)),
                ('valore', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chiave', models.CharField(max_length=50, unique=True)),
                ('valore', models.CharField(max_length=100)),
            ],
        ),
    ]
