# Generated by Django 5.2.4 on 2025-07-15 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0008_categoria_opzione_sottocategoria_stato'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parametri',
        ),
    ]
