# Generated by Django 5.2.4 on 2025-07-15 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0010_alter_prodotto_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodotto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='prodotto',
            name='sottocategoria',
        ),
    ]
