# Generated by Django 5.2.4 on 2025-07-15 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0011_remove_prodotto_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodotto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bar.categoria'),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='sottocategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bar.sottocategoria'),
        ),
    ]
