# Generated by Django 5.2.4 on 2025-07-15 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0012_prodotto_categoria_prodotto_sottocategoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordine',
            name='stato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bar.stato'),
        ),
        migrations.AlterField(
            model_name='ordineriga',
            name='opzioni',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bar.opzione'),
        ),
        migrations.AlterField(
            model_name='ordineriga',
            name='stato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bar.stato'),
        ),
    ]
