# Generated by Django 5.2.4 on 2025-07-15 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0013_alter_ordine_stato_alter_ordineriga_opzioni_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordine',
            name='stato',
        ),
    ]
