# Generated by Django 5.2.4 on 2025-07-15 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0014_remove_ordine_stato'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordine',
            name='stato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bar.stato'),
        ),
    ]
