# Generated by Django 5.2.4 on 2025-07-24 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0015_ordine_stato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magazzino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('quantita', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='prodotto',
            name='magazzino',
            field=models.ForeignKey(blank=True, help_text='Se impostato, questo prodotto consumerà questa voce di magazzino', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bar.magazzino'),
        ),
    ]
