# Generated by Django 5.2.4 on 2025-07-25 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0016_magazzino_prodotto_magazzino'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodotto',
            name='magazzino',
        ),
        migrations.CreateModel(
            name='ComponenteMagazzino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita_utilizzata', models.FloatField()),
                ('percentuale_maggiorazione', models.FloatField(default=0)),
                ('magazzino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bar.magazzino')),
                ('prodotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bar.prodotto')),
            ],
        ),
        migrations.AddField(
            model_name='prodotto',
            name='componenti_magazzino',
            field=models.ManyToManyField(related_name='distinta_base', through='bar.ComponenteMagazzino', to='bar.magazzino'),
        ),
    ]
