# Generated by Django 5.2.4 on 2025-07-25 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0017_remove_prodotto_magazzino_componentemagazzino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentemagazzino',
            name='bloccante',
            field=models.BooleanField(default=True, help_text="Se attivo, l'esaurimento blocca la preparazione"),
        ),
    ]
