# Generated by Django 5.2.4 on 2025-07-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0018_componentemagazzino_bloccante'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazzino',
            name='soglia_minima',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
