# Generated by Django 5.2.4 on 2025-07-25 09:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0019_magazzino_soglia_minima'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazzino',
            name='quantita',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
