# Generated by Django 5.2.4 on 2025-07-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0022_ordineriga_utente'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodotto',
            name='costo_produzione',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Costo fisso di produzione'),
        ),
    ]
