# Generated by Django 5.2.4 on 2025-07-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0023_prodotto_costo_produzione'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodotto',
            name='costo_produzione',
        ),
        migrations.AddField(
            model_name='componentemagazzino',
            name='costo_produzione',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Costo di acquisto'),
        ),
    ]
