# Generated by Django 5.2.4 on 2025-07-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0024_remove_prodotto_costo_produzione_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componentemagazzino',
            name='costo_produzione',
        ),
        migrations.AddField(
            model_name='magazzino',
            name='costo_acquisto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Costo di acquisto'),
        ),
    ]
