# Generated by Django 5.2.4 on 2025-08-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0025_remove_componentemagazzino_costo_produzione_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodotto',
            name='stato',
            field=models.CharField(choices=[('valido', 'Valido'), ('annullato', 'Annullato')], default='valido', max_length=10),
        ),
    ]
