# Generated by Django 5.2.4 on 2025-08-07 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0026_prodotto_stato'),
    ]

    operations = [
        migrations.AddField(
            model_name='sottocategoria',
            name='opzioni_abilitate',
            field=models.ManyToManyField(blank=True, related_name='sottocategorie', to='bar.opzione'),
        ),
    ]
