# Generated by Django 5.2.4 on 2025-08-07 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0027_sottocategoria_opzioni_abilitate'),
    ]

    operations = [
        migrations.AddField(
            model_name='sottocategoria',
            name='flag_subito_completato',
            field=models.BooleanField(default=False),
        ),
    ]
