# Generated by Django 5.2.4 on 2025-08-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0029_postazione_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='postazione',
            name='sottocategorie',
            field=models.ManyToManyField(blank=True, related_name='sottocategorie', to='bar.sottocategoria'),
        ),
        migrations.AlterField(
            model_name='sottocategoria',
            name='opzioni_abilitate',
            field=models.ManyToManyField(blank=True, related_name='opzioni_abilitate', to='bar.opzione'),
        ),
    ]
