# Generated by Django 5.2.4 on 2025-08-08 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0030_postazione_sottocategorie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postazione',
            name='sottocategorie',
        ),
        migrations.AddField(
            model_name='postazione',
            name='sottocategorie_associate',
            field=models.ManyToManyField(blank=True, related_name='sottocategorie_associate', to='bar.sottocategoria'),
        ),
    ]
