# Generated by Django 5.2.4 on 2025-08-09 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0031_remove_postazione_sottocategorie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sottocategoria',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bar.categoria'),
        ),
    ]
