# Generated by Django 5.2.4 on 2025-08-09 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0032_sottocategoria_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodotto',
            name='categoria',
        ),
    ]
