# Generated by Django 5.2.4 on 2025-08-12 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0033_remove_prodotto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chiave', models.CharField(max_length=50, unique=True)),
                ('valore', models.CharField(max_length=100)),
                ('is_free', models.BooleanField(default=True)),
                ('postazione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bar.postazione')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
