# Generated by Django 5.2.4 on 2025-08-13 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0034_box'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='postazione',
        ),
        migrations.AddField(
            model_name='postazione',
            name='box_associati',
            field=models.ManyToManyField(blank=True, related_name='box_associati', to='bar.box'),
        ),
    ]
