# Generated by Django 5.2.4 on 2025-08-13 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0035_remove_box_postazione_postazione_box_associati'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordineriga',
            name='box_associato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bar.box'),
        ),
    ]
