# Generated by Django 5.2.4 on 2025-08-14 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0036_ordineriga_box_associato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='is_free',
        ),
        migrations.AddField(
            model_name='box',
            name='attivo',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='BoxAllocazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attivo', models.BooleanField(default=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bar.box')),
                ('ordine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bar.ordine')),
                ('postazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bar.postazione')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('ordine', 'postazione', 'attivo'), name='unique_active_box_per_postazione_ordine')],
            },
        ),
    ]
