# Generated by Django 5.2.4 on 2025-08-15 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0037_remove_box_is_free_box_attivo_boxallocazione'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordineriga',
            name='box_associato',
        ),
        migrations.AddField(
            model_name='sottocategoria',
            name='postazione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bar.postazione'),
        ),
    ]
