# Generated by Django 5.2.4 on 2025-08-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0038_remove_ordineriga_box_associato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='codice',
            field=models.CharField(default='', max_length=100),
        ),
    ]
